// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysftdjcnmlrmjmtsqnhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzZnRkamNubWxybWptdHNxbmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTcyMjMsImV4cCI6MjA2MzY3MzIyM30.2xTVyOwrpgcniWGmXDM1wdrk9wZ_bFYCCHF_nIQ6ZT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
